from pathlib import Path
import json, hashlib
p=Path(__file__).resolve().parent
search=json.loads((p/'search.json').read_text())
entries=[json.loads((p/('read-'+x+'.json')).read_text()) for x in ['math.cauchy-schwarz','math.score-difference-bound','math.topk-margin']]
refs={r['id']:r for e in entries for r in e['knowledge_refs']}
use={'schema_version':1,'task_id':'KB-LIVE-1','input_version':'synthetic-dot-products-v1','role':'research-review','decision':'EXECUTE','status':'used','knowledge_root':'knowledge','knowledge_tool':'python -m agent_runtime.knowledge','corpus_snapshot':search['snapshot'],'backend':search['backend'],'queries':[{'query':'dot product vector error norm topk gap','output':'search.json'}],'commands_file':'commands.json','knowledge_refs':list(refs.values()),'read_entries':[{'id':e['id'],'artifact':'read-'+e['id']+'.json','requires':e['requires']} for e in entries],'assumptions':[{'assumption':'Common-dimensional real vectors and a fixed query','status':'explicit_interpretation','evidence':'Real q^T k_i in trusted task; producer explicitly holds q fixed.'},{'assumption':'Euclidean norm (or a valid dual norm pairing)','status':'conditional','evidence':'Task says norm but does not specify which; Euclidean interpretation is conventional and must be labeled.'},{'assumption':'Finite score list and 1<=k<n','status':'implicit_in_boundary_gap','evidence':'Positive top-k boundary gap presupposes a nontrivial boundary; task does not literally state n or k.'},{'assumption':'Uniform per-vector bound in first case','status':'satisfied','evidence':'task.json each_vector_error_norm_bound=0.02'},{'assumption':'Mean means arithmetic mean of individual error norms','status':'explicit_interpretation','evidence':'Producer clearly states this interpretation.'},{'assumption':'Global score l2 error <=0.06','status':'not_established','evidence':'Per-vector uniform norm bounds do not imply that global bound; REV-C08.'}],'adoption_decisions':[{'id':'math.cauchy-schwarz','decision':'adopt_conditionally','reason':'Valid for Euclidean interpretation; independent squared-norm derivation checked.'},{'id':'math.topk-margin','decision':'adopt','reason':'Cross-boundary proof directly yields gap>=0.03 under uniform bounds.'},{'id':'math.score-difference-bound','decision':'reject_numeric_application','reason':'No global l2 error bound supplied; warning is relevant.'}],'verification_artifacts':['independent_verify.py','independent-output.json','review.md'],'limitations':['No network or external source verification.','No full manuscript or venue review.','No formal theorem prover or model/performance claim.','Hashes establish content identity, not applicability.']}
(p/'knowledge-use.json').write_text(json.dumps(use,indent=2))
finding={'finding_id':'REV-F001','severity':'minor','confidence':'high','category':'provenance_and_assumption_reporting','assertion_type':'confirmed_reporting_gap','status':'open','location':['producer/knowledge-use.json input_version and assumptions','producer/answer.md assumptions table'],'evidence':['Trusted request/handoff input_version is synthetic-dot-products-v1; producer knowledge-use input_version is synthetic-dot-product-task-v1.','Trusted task does not explicitly specify Euclidean/2-norm, n>=2 or k range; producer labels these as given explicit constraints.'],'impact':'Mathematics is correct conditionally, but current record overstates alignment and explicit applicability to the trusted input.','repair_conditions':['Preserve original evidence and supply an explicit version/task mapping to KB-LIVE-1 and synthetic-dot-products-v1, or a newly versioned corrected record.','State fixed-query/common-dimensional Euclidean norms as the interpretation used; distinguish implicitly necessary finite nontrivial top-k boundary from literally supplied constraints.','Publish a new immutable handoff including the resolution; independent reviewer rechecks it.'],'not_findings':['Whole-corpus snapshot differs between producer and reviewer, but all three retrieved dependency refs agree; no stale required entry established.','Producer runtime reproduction paths are not reviewed as present or absent; supplied copied script was read and reviewer script independently executed.']}
(p/'findings.json').write_text(json.dumps({'findings':[finding]},indent=2))
(p/'review.md').write_text('''# Scoped review — KB-LIVE-1

Review date: 2026-10-07. Decision: **needs_revision for provenance/assumption reporting; mathematical claims pass under the stated Euclidean interpretation.** Provisional correctness and reproducibility rubric; no venue or full manuscript assessment.

## Materials and actual actions

Read trusted task.json, request.json and plan.json; AGENTS.md/TASK.md and the assigned research-review guidance. Consumed seq 1 with the actual Mailbox CLI using consumer-owned request and corpus. Read every artifact returned in consumed-handoff.json, including answer, knowledge usage, local retrieval output, verification script and output. Independently searched the current knowledge corpus, read all three relevant entries and prerequisite closure through the CLI, and executed independent_verify.py. No repository tests or previous evaluation documents were read or run. TASK.md contains historical summaries; linked historical artifacts were not opened.

## Scientific assessment

For any selected i and unselected j, write e_i = q^T(khat_i-k_i). Under a common-dimensional Euclidean norm and unchanged q, Cauchy–Schwarz follows by minimizing the nonnegative squared norm ||q-t d||² in t (zero d is trivial). Hence |e_i| <= 3*0.02 = 0.06. The perturbed cross-boundary difference is at least 0.15-|e_i|-|e_j| >= 0.03 > 0. This proves unchanged membership for every such pair and does not prove internal ordering. The strict inequality handles boundary ties correctly.

For the arithmetic mean of individual error norms, total error is at most n*0.02, so pairwise score loss is at most 3*n*0.02. The given values certify n=2, while the producer's n=3 example has exact mean 0.02, original scores (0.15,0,-3), and replacement scores (-0.03,0,-3), strictly changing top-1. A second independently constructed example splits error 0.03 across both boundary keys and also reverses the pair with mean 0.02. Failure of the sufficient bound is not itself a reversal proof. No unjustified sqrt(2)*0.06 global-norm certificate was applied.

The nine reviewer-owned rational checks pass (REV-C01–REV-C09, independent-output.json). Finite checks verify arithmetic and counterexamples; the argument above supplies the general inequality reasoning. Producer checks were not treated as truth merely because they passed or had matching hashes.

## Required reporting repair — REV-F001

The producer knowledge-use.json says input_version `synthetic-dot-product-task-v1`; the trusted request/handoff says `synthetic-dot-products-v1`. Also, answer.md and knowledge-use.json call a 2-norm and n/k constraints explicit task givens, whereas the trusted task.json only says norm and a top-k boundary gap. The Euclidean interpretation is reasonable, but it must be distinguished from the exact supplied evidence. The producer already makes the arithmetic-mean interpretation clear.

This is a minor, confirmed traceability and assumption-reporting gap, not a counterexample to the conditional mathematics. Close it by preserving the old records and adding a precise source-version mapping or new corrected record, explicitly identifying adopted interpretations, then issuing a new immutable handoff for independent recheck. Root owns repair; reviewer does not edit producer files. findings.json records stable ID, evidence, and acceptance conditions.

## Boundaries and next action

All three required/used entry IDs, versions and content hashes agree in the current independent retrieval. Whole-corpus snapshot changed; this alone does not establish staleness of these entries and was not counted as a defect. Local source metadata is not fresh external source verification. No network, formal prover, model quality comparison, performance claim, full manuscript/PDF review, daemon or server deployment is involved.

Root should resolve REV-F001 and publish a new event. Receipt for seq 1 is needs_revision, exported after ACK through actual Mailbox status. The original event and producer artifacts remain unchanged. Repository requirements implicated: KB-ACCESS-01 (actual retrieval and applicability evidence) and KB-ACCESS-03 (actual scoped role use). This review does not complete the broader root requirements.
''')
commands=[{'command':['python','-m','agent_runtime.communication','--db','.agent-runs/knowledge-access-live/mail.sqlite','--plan','docs/knowledge_access_validation/live/plan.json','--root','.','consume','research-review','1','--request','docs/knowledge_access_validation/live/request.json'],'returncode':0,'stdout':'consumed-handoff.json'},{'command':['python','-m','agent_runtime.knowledge','--root','knowledge','search','dot product vector error norm topk gap','--limit','3'],'returncode':0,'stdout':'search.json'}]+json.loads((p/'retrieval-commands.json').read_text())+[{'command':['python','docs/knowledge_access_validation/live/reviewer/independent_verify.py'],'returncode':0,'stdout':'independent-output.json'}]
(p/'commands.json').write_text(json.dumps({'cwd':str(p.parents[3]),'commands':commands,'scope':'Actual command/output evidence; see receipt commands for subsequent ACK/readback.'},indent=2))
(p/'receipt-request.json').write_text(json.dumps({'status':'needs_revision','reason':'REV-F001: conditional mathematics independently verified (9 exact checks), but producer usage input_version differs from trusted request and claims norm/n-k assumptions explicitly supplied when they are interpretations. Preserve originals, supply mapping/assumption clarification and new immutable handoff for recheck. Review: docs/knowledge_access_validation/live/reviewer/review.md'},indent=2))
