import pathlib,json,hashlib,csv
from agent_runtime.communication import Mailbox
R=pathlib.Path.cwd();H=R/'docs/continuous_optimization/rounds/2026-10-07-revision-handoff/evidence/w9-release/handoff';O=H/'review-final';C=json.loads((H/'host-context.json').read_text());B=Mailbox(C['db'],C['plan'],C['artifact_root'])
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):
 with (O/n).open('x') as f:json.dump(v,f,ensure_ascii=False,indent=2)
save('status-before.json',B.status());inbox=B.inbox('research-review');save('inbox.json',inbox)
assert len(inbox)==1 and inbox[0]['seq']==3
E=inbox[0]['event'];assert (E['sender'],E['task_id'],E['input_version'],E['run_id'])==('research-write','REV-03','synthetic-manuscript-v1',C['plan']['run_id'])
expected={'writer/handoff.json':'151bc7139030ac658f971093bd7ca0c5f966f9aac1dc0ffad21797cd8d26e937','writer/manuscript-revised.md':'41b853ec61746724fd487d714b34e11778c5ad83a25d20ab31a20d784391cb60'}
for p,h in expected.items():assert sha(H/p)==h and any(r['path']==p and r['sha256']==h for r in E['refs'])
for r in E['refs']:assert sha(H/r['path'])==r['sha256']
request=dict(schema_version=1,input_version='synthetic-manuscript-v1',tasks=[dict(task_id='REV-03',allow_skip=False)],expected_sender='research-write',intended_recipient='research-review',permitted_revision_refs=expected,authority='Trusted root followup, independently supplied before consumption')
save('consumer-request.json',request)
record=B.consume_handoff('research-review',3,request,require_complete=True);save('consume-handoff-result.json',record);save('status-after-validation-before-ack.json',B.status())
old=H/'inputs/manuscript.md';new=H/'writer/manuscript-revised.md';data=H/'inputs/measurements.csv';original=H/'review-initial/original-findings.yaml'
assert sha(old)=='712dd94ef8f5ad0c1a6f5f36bb3735901fc6bce564a96381cf6e4cfdc68ce88e'
assert sha(data)=='57201d75a6e7ea0b7581c2d94f4bf46c2b9a66e37b5df94c8e6b4c5ef3924248'
old_text=old.read_text();new_text=new.read_text();original_findings=json.loads(original.read_text())['findings']
computations=[]
for row in csv.DictReader(data.open()):
 b,c=float(row['baseline_ms']),float(row['candidate_ms']);computations.append(dict(workload=row['workload'],scope=row['scope'],baseline_ms=b,candidate_ms=c,speedup=b/c,latency_change_percent=100*(c-b)/b))
save('independent-calculations.json',dict(source_sha256=sha(data),method='baseline/candidate; 100*(candidate-baseline)/baseline; no timing scopes summed',rows=computations,observed_new_table='New manuscript lines 21–24 match all supplied rows and derived arithmetic at shown rounding.',new_abstract_and_appendix='New lines 7 and 34 match table and source.'))
versions=dict(old_manuscript=dict(path='inputs/manuscript.md',sha256=sha(old)),new_manuscript=dict(path='writer/manuscript-revised.md',sha256=sha(new)),csv=dict(path='inputs/measurements.csv',sha256=sha(data)),original_findings=dict(path='review-initial/original-findings.yaml',sha256=sha(original)))
checks=[dict(finding_id='REV-F001',original_status='confirmed',result='resolved',original_acceptance=original_findings[0]['acceptance'],locations=['writer/manuscript-revised.md line 7 Abstract','lines 21–26 Results','line 34 Appendix A'],evidence=['Abstract now lists end-to-end 1.25x, 1.20x, approximately 0.90909x, and explicitly the 10% large-workload latency regression.','Results table preserves 100/80,120/100,200/220 and separate kernel20/10; independent recalculation agrees.','Abstract, Results and Appendix explicitly restrict 2x to kernel-only and forbid adding included kernel latency to end-to-end timing.'],acceptance_met=True,decision='Core abstract inconsistency corrected across all requested sections; no new empirical claim introduced.'),dict(finding_id='REV-F002',original_status='confirmed',result='resolved',original_acceptance=original_findings[1]['acceptance'],locations=['line 3 scope statement','line 7 Abstract','lines 11–13 Method','line 26 Results','line 30 Evidence limits','line 34 Appendix A'],evidence=['Every positive/negative performance observation is framed as supplied single-run CPU records.','No independent repeats, variance/quality unmeasured and no GPU measurement remain explicit.','Line 30 rejects CI, significance, repeatability and quality-preservation inference; no invented data, raw logs or experiments provided.','Original condition allowed descriptive scope as sufficient resolution; new experiments were not necessary and none were requested in this bounded revision.'],acceptance_met=True,decision='Existing-data/descriptive-scope branch of original acceptance is satisfied; actual repeatability and quality remain unknown, not established.'),dict(finding_id='REV-F003',original_status='rejected',result='rejected',original_acceptance=original_findings[2]['acceptance'],locations=['inputs/manuscript.md line 10','writer/manuscript-revised.md line 34'],evidence=['Old Appendix already discloses 200 ms to 220 ms regression.','New Appendix retains that disclosure and explicitly states correction is to inconsistent abstract, not a hidden/omitted result.'],acceptance_met=True,decision='Original rejection preserved; no claim that this nonexistent omission was repaired.')]
save('recheck-findings.json',dict(run_id=E['run_id'],input_version=E['input_version'],reviewer='research-review (same original reviewer)',versions=versions,checks=checks,counts=dict(resolved=2,rejected=1,open=0,unresolved=0,blocked=0),scientific_scope='Only original bounded manuscript consistency/scope findings; no new empirical validation or publication endorsement.',basis='Actual independent old/new/data reading plus recalculation, completed before ACK.'))
(O/'recheck-report.md').write_text('# Original-reviewer recheck · revision 1\n\nRead the complete old and revised manuscript, unchanged CSV, and original independent findings. Verified trusted root manifest/manuscript hashes against actual seq 3 refs, then successfully called consume_handoff with the independent REV-03 consumer contract. That validation did not acknowledge delivery or close findings.\n\n- REV-F001 resolved: new Abstract line 7, Results lines 21–26 and Appendix line 34 consistently report end-to-end 1.25x/1.20x/0.90909x, large 10% regression and separate kernel-only 2x. Independent CSV arithmetic agrees.\n- REV-F002 resolved through the originally allowed descriptive-scope branch: lines 3, 7, 11–13, 26, 30 and 34 keep all results as single-run synthetic CPU observations, with no independent repeats, variance/quality measurements or GPU evidence. There are no fabricated intervals, new experiments, universal gains or repeatability claims. This resolves overclaiming, not the empirical unknowns themselves.\n- REV-F003 remains rejected: original Appendix line 10 already disclosed regression; revised Appendix line 34 retains it and does not claim to repair an omission.\n\nCounts: 2 resolved, 1 rejected, 0 open/unresolved/blocked. Original findings and representative outputs remain unchanged. New closure records bind original IDs and old/new/data hashes in recheck-findings.json. No final PDF was requested for this bounded Markdown revision; no PDF visual review is claimed. No novelty, implementation or new measurement validation occurred.\n\nThe semantic recheck above is the basis for closure. Subsequent consumed ACK records message handling only.\n')
trace=dict(loaded_files=[dict(path=str(p.relative_to(R)),sha256=sha(p)) for p in [R/'workflows/agent_communication_workflow.md',H/'host-context.json',H/'writer/handoff.json',new,old,data,original,H/'writer/evidence-mapping.json',R/'agent_runtime/communication.py',R/'scripts/validate_handoff.py']],tool_trace=['0f13d7: full workflow and host context read; consume_handoff implementation read','ea70b7: actual research-review inbox seq3 and status read','6ef685: full old/new manuscripts, CSV and original findings read; rg guessed wrong runtime glob and exited 2; no state mutation','7b4e2c: correct validate_handoff module identified; writer mapping read only after independent original/new reading','ec39d5: consumer-request schema inspected','recheck.py: trusted hashes and complete task contract validated; independent arithmetic and per-ID semantic record written before ACK'],recoverable_failures=[dict(tool_chunk='6ef685',failure='rg agent_runtime/handoff* did not match',impact='None on semantic reading; corrected to scripts/validate_handoff.py')],boundaries=['No original or representative output mutation','No new experiment/network/install','No closure inferred from delivery/ACK','Same original reviewer owns recheck'])
save('provenance.json',trace)
receipt=dict(status='consumed',reason='Original research-review independently read old/new manuscript and unchanged CSV, recalculated all ratios, and recorded hash-bound original-condition recheck in review-final/recheck-findings.json before ACK: REV-F001 and REV-F002 resolved by corrected descriptive claims; REV-F003 remains rejected. This receipt records handling only and is not the basis of scientific closure.')
save('receipt.json',receipt)
# Separate mailbox handling from the completed semantic recheck above.
B.acknowledge('research-review',3,receipt)
save('status-after-ack.json',B.status());save('inbox-after-ack.json',B.inbox('research-review'))
save('completion.json',dict(incoming_seq=3,event_id=E['event_id'],receipt=receipt,counts=dict(resolved=2,rejected=1,remaining=0,blocked=0),semantic_record=dict(path='review-final/recheck-findings.json',sha256=sha(O/'recheck-findings.json')),pending_research_review=len(B.inbox('research-review'))))
print(json.dumps(dict(counts=dict(resolved=2,rejected=1,remaining=0,blocked=0),seq3_receipt=receipt,status=B.status()),indent=2))
