#!/usr/bin/env python3
"""Regenerate plugin-bundled workflow references from repository sources.

The top-level workflows are the source of truth. Bundled plugin references use
local bundled links where available, with GitHub links as a fallback.
The figure family's complete standalone snapshots retain exact source bytes.
"""
from __future__ import annotations

import argparse
import posixpath
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_BLOB = "https://github.com/Chosen-David/agent/blob/main/"
GENERATED = "<!-- GENERATED by scripts/sync_plugin_references.py; edit the source workflow instead. -->\n\n"

MAPPINGS = {
    "workflows/data_visualization_learning.md": [
        f"plugins/research-assistant/skills/{role}/references/data_visualization_learning.md"
        for role in ("research-data-visualization", "research-figures", "research-assistant", "research-write", "research-review", "research-read-pdf", "research-diagrams")
    ],
    "workflows/experiment_execution_contract.md": [
        "plugins/research-assistant/skills/research-implement-optimize/references/experiment_execution_contract.md",
        "plugins/research-assistant/skills/research-assistant/references/experiment_execution_contract.md",
    ],
    "workflows/paper_exemplar_learning.md": [
        f"plugins/research-assistant/skills/{role}/references/paper_exemplar_learning.md"
        for role in ("research-assistant", "research-write", "research-review", "research-read-pdf", "research-diagrams", "research-figures", "research-data-visualization")
    ],
    "workflows/task_supervision_workflow.md": [
        "plugins/research-assistant/skills/research-assistant/references/task_supervision_workflow.md",
    ],
    "workflows/paper_delivery_contract.md": [
        f"plugins/research-assistant/skills/{role}/references/paper_delivery_contract.md"
        for role in ("research-assistant", "research-write", "research-review", "research-read-pdf")
    ],
    "plugins/research-assistant/skills/code-reading/references/coverage.example.json": [
        "plugins/research-assistant/skills/research-assistant/references/code_reading_coverage.example.json",
    ],
    "plugins/research-assistant/skills/code-reading/references/coverage.md": [
        "plugins/research-assistant/skills/research-assistant/references/code_reading_coverage.md",
        "plugins/research-assistant/skills/research-implement-optimize/references/code_reading_coverage.md",
    ],
    "workflows/code_reading_workflow.md": [
        "plugins/research-assistant/skills/code-reading/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/code_reading_workflow.md",
        "plugins/research-assistant/skills/research-implement-optimize/references/code_reading_workflow.md",
    ],
    "prompts/research_orchestrator.md": [
        "plugins/research-assistant/skills/research-assistant/references/orchestrator.md",
    ],
    "templates/project_brief.md": [
        "plugins/research-assistant/skills/research-assistant/references/project_brief.md",
    ],
    "workflows/research_workflow.md": [
        "plugins/research-assistant/skills/research-explore/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/research_workflow.md",
    ],
    "workflows/implementation_optimization_workflow.md": [
        "plugins/research-assistant/skills/research-implement-optimize/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/implementation_optimization_workflow.md",
    ],
    "workflows/figure_workflow.md": [
        "plugins/research-assistant/skills/research-figures/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/figure_workflow.md",
    ],
    "workflows/paper_writing_workflow.md": [
        "plugins/research-assistant/skills/research-write/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/paper_writing_workflow.md",
    ],
    "workflows/reviewer_workflow.md": [
        "plugins/research-assistant/skills/research-review/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/reviewer_workflow.md",
    ],
    "workflows/reader_workflow.md": [
        "plugins/research-assistant/skills/research-read-pdf/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/reader_workflow.md",
    ],
    "workflows/paper_reading_companion_workflow.md": [
        "plugins/research-assistant/skills/paper-reading-companion/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/paper_reading_companion_workflow.md",
    ],
    "workflows/concept_explanation_workflow.md": [
        "plugins/research-assistant/skills/explain-research-concepts/references/workflow.md",
        "plugins/research-assistant/skills/paper-reading-companion/references/concept_explanation_workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/concept_explanation_workflow.md",
    ],
}

# The figure split deliberately uses exact, locally closed workflow snapshots.
# Preserve this contract rather than converting their local links into URLs.
FIGURE_COMMON = ('figure_shared.md', 'figure_tools.md', 'figure_inputs.md')
FIGURE_SPECIALISTS = {
    'research-data-visualization': 'data_visualization_workflow.md',
    'research-diagrams': 'diagram_workflow.md',
}
RAW_COPY_SOURCES = {'workflows/' + name for name in (
    'figure_workflow.md', *FIGURE_COMMON, *FIGURE_SPECIALISTS.values())}
for filename in FIGURE_COMMON:
    MAPPINGS['workflows/' + filename] = [
        f'plugins/research-assistant/skills/{role}/references/{filename}'
        for role in ('research-assistant', 'research-figures', *FIGURE_SPECIALISTS)
    ]
for role, filename in FIGURE_SPECIALISTS.items():
    MAPPINGS['workflows/' + filename] = [
        f'plugins/research-assistant/skills/{role}/references/workflow.md',
        f'plugins/research-assistant/skills/research-figures/references/{filename}',
        f'plugins/research-assistant/skills/research-assistant/references/{filename}',
    ]

# The coordinator bundles role supplements for standalone/offline dispatch.
import json
for role in json.loads((ROOT / "config/role_registry.json").read_text())["roles"]:
    if role["id"] not in {"research-assistant", "travel-planner"}:
        MAPPINGS[role["execution"]] = [
            "plugins/research-assistant/skills/research-assistant/references/"
            + role["id"] + "_execution.md"
        ]

LINK_RE = re.compile(r"(!?\[[^\]]*\]\()([^)]+)(\))")


def _rewrite_target(source: str, target: str, destination: str | None = None) -> str:
    target = target.strip()
    if target.startswith(("http://", "https://", "mailto:", "#", "data:")):
        return target
    if " " in target and not target.startswith("<"):
        # Avoid rewriting markdown targets with optional titles.
        return target
    raw = target[1:-1] if target.startswith("<") and target.endswith(">") else target
    path, sep, anchor = raw.partition("#")
    resolved = posixpath.normpath(posixpath.join(posixpath.dirname(source), path))
    if resolved.startswith("../"):
        return target
    if destination:
        # Preserve a self-contained skill when that source is bundled locally.
        skill_root = destination.split('/references/')[0] + '/'
        candidates = [resolved] + MAPPINGS.get(resolved, [])
        for candidate in candidates:
            if candidate.startswith(skill_root):
                local = posixpath.relpath(candidate, posixpath.dirname(destination))
                return local + (("#" + anchor) if sep else "")
    url = REPO_BLOB + resolved + (("#" + anchor) if sep else "")
    return "<" + url + ">" if target.startswith("<") else url


def render(source: str, destination: str | None = None) -> str:
    text = (ROOT / source).read_text(encoding="utf-8")
    if source in RAW_COPY_SOURCES or source.endswith('.json'):
        return text
    text = LINK_RE.sub(lambda m: m.group(1) + _rewrite_target(source, m.group(2), destination) + m.group(3), text)
    return GENERATED + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated references are stale")
    args = parser.parse_args()
    stale = []
    for source, destinations in MAPPINGS.items():
        for destination in destinations:
            expected = render(source, destination)
            path = ROOT / destination
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual == expected:
                continue
            stale.append(destination)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
    if args.check and stale:
        print("stale generated references:")
        for item in stale:
            print(" -", item)
        return 1
    if stale and not args.check:
        print("updated", len(stale), "generated references")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
