#!/usr/bin/env python3
"""Regenerate plugin-bundled workflow references from repository sources.

The top-level workflows are the source of truth. Bundled plugin references use
absolute GitHub links so they remain useful after the plugin is packaged away
from the repository root.
"""
from __future__ import annotations

import argparse
import posixpath
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_BLOB = "https://github.com/Chosen-David/agent/blob/main/"
GENERATED = "<!-- GENERATED by scripts/sync_plugin_references.py; edit the source workflow instead. -->\n\n"

MAPPINGS = {
    "prompts/research_orchestrator.md": [
        "plugins/research-assistant/skills/research-assistant/references/orchestrator.md",
    ],
    "templates/project_brief.md": [
        "plugins/research-assistant/skills/research-assistant/references/project_brief.md",
    ],
    "workflows/research_workflow.md": [
        "plugins/research-assistant/skills/research-explore/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/research_workflow.md",
    ],
    "workflows/implementation_optimization_workflow.md": [
        "plugins/research-assistant/skills/research-implement-optimize/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/implementation_optimization_workflow.md",
    ],
    "workflows/figure_workflow.md": [
        "plugins/research-assistant/skills/research-figures/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/figure_workflow.md",
    ],
    "workflows/paper_writing_workflow.md": [
        "plugins/research-assistant/skills/research-write/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/paper_writing_workflow.md",
    ],
    "workflows/reviewer_workflow.md": [
        "plugins/research-assistant/skills/research-review/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/reviewer_workflow.md",
    ],
    "workflows/reader_workflow.md": [
        "plugins/research-assistant/skills/research-read-pdf/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/reader_workflow.md",
    ],
    "workflows/paper_reading_companion_workflow.md": [
        "plugins/research-assistant/skills/paper-reading-companion/references/workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/paper_reading_companion_workflow.md",
    ],
    "workflows/concept_explanation_workflow.md": [
        "plugins/research-assistant/skills/explain-research-concepts/references/workflow.md",
        "plugins/research-assistant/skills/paper-reading-companion/references/concept_explanation_workflow.md",
        "plugins/research-assistant/skills/research-assistant/references/concept_explanation_workflow.md",
    ],
    "workflows/travel_planning_workflow.md": [
        "plugins/travel-assistant/skills/travel-planner/references/workflow.md",
    ],
    "templates/travel_brief.md": [
        "plugins/travel-assistant/skills/travel-planner/references/travel_brief.md",
    ],
}

LINK_RE = re.compile(r"(!?\[[^\]]*\]\()([^)]+)(\))")


def _rewrite_target(source: str, target: str) -> str:
    target = target.strip()
    if target.startswith(("http://", "https://", "mailto:", "#", "data:")):
        return target
    if " " in target and not target.startswith("<"):
        # Avoid rewriting markdown targets with optional titles.
        return target
    raw = target[1:-1] if target.startswith("<") and target.endswith(">") else target
    path, sep, anchor = raw.partition("#")
    resolved = posixpath.normpath(posixpath.join(posixpath.dirname(source), path))
    if resolved.startswith("../"):
        return target
    url = REPO_BLOB + resolved + (("#" + anchor) if sep else "")
    return "<" + url + ">" if target.startswith("<") else url


def render(source: str) -> str:
    text = (ROOT / source).read_text(encoding="utf-8")
    text = LINK_RE.sub(lambda m: m.group(1) + _rewrite_target(source, m.group(2)) + m.group(3), text)
    return GENERATED + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated references are stale")
    args = parser.parse_args()
    stale = []
    for source, destinations in MAPPINGS.items():
        expected = render(source)
        for destination in destinations:
            path = ROOT / destination
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual == expected:
                continue
            stale.append(destination)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
    if args.check and stale:
        print("stale generated references:")
        for item in stale:
            print(" -", item)
        return 1
    if stale and not args.check:
        print("updated", len(stale), "generated references")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
