from pathlib import Path
import json
p=Path(__file__).parent
run='research-assistant-candidate-0001-v2'
def t(id,dep,refs,inputs,action,out,accept,status='todo',reason=None):
 return {'task_id':id,'stage':id.split('-')[0],'depends_on':dep,'owner':'current_coordinator' if status=='done' else 'host-assigned-single-owner-required','inputs':inputs,'input_version':'measurements.csv@v2' if not id.startswith('BG') else 'concept.txt@v1','action':action,'outputs':out,'done_when':accept,'acceptance':accept,'on_failure':'preserve evidence; diagnose once; stop this branch on second failure; continue independent nodes','on_missing_input':reason or 'block affected node; report exact missing input','resource_budget':{'cpu_only':True,'new_experiments':0,'network':False,'installations':False,'external_services':0,'max_attempts':2},'status':status,'status_reason':reason,'task_refs':refs,'report_path':'report.md','verification_scope':'local performed work; not independent host acceptance' if status=='done' else 'planned only'}
base=['project.json:goal','task.txt:dependency-analysis']
nodes=[
t('RES-INPUT-v2',[],['project.json:change','project.json:state.collect'],['project.json','measurements.csv@v2'],'Freeze file hashes; parse columns, positive ms, unique workload, scopes',['loaded_references.json','calculation_log.json'],'Four source records parse; hashes identify actual bytes; synthetic classification retained','done'),
t('RES-IMPACT-v2',['RES-INPUT-v2'],['project.json:state.collect','project.json:state.figure','project.json:state.write','project.json:state.background'],['project.json','concept.txt@v1','measurements.csv@v2'],'Trace declared input dependency changes without asserting absent output validation',['report.md'],'Keep historical collect/background declarations; invalidate current-use figure/write v1; explicitly record absent v1 bytes','done'),
t('RES-CALC-v2',['RES-INPUT-v2'],base,['measurements.csv@v2'],'Calculate per-row speedup and latency reduction; scope-separate diagnostic aggregate',['calculate.py','results.csv','results.json','calculation_log.json'],'All four rows included; kernel excluded from end-to-end aggregate; equal-once assumption disclosed','done'),
t('RES-CHECK-v2',['RES-CALC-v2'],base,['measurements.csv@v2','results.json'],'Recompute via Fraction using separately written verifier; validate DAG and refs',['verify_calculation.py','verification.json'],'Numerical comparisons pass within 1e-12; dependency IDs exist and DAG acyclic','done'),
t('RES-DECIDE-v2',['RES-CHECK-v2','RES-IMPACT-v2'],base,['results.json'],'Form bounded continuation recommendation; identify large regression, retain baseline; state unknown real-world decision',['report.md'],'No all-workload claim, no synthetic-to-real inference, no new optimization experiments','done'),
t('WRITE-DRAFT-v2',['RES-DECIDE-v2'],['project.json:state.write'],['results.json'],'Write bounded results draft independently of pending figure; mark final write still pending',['report.md'],'Contains all scopes, large regression and synthetic/no-replicate limits; no ungenerated figure cited','done'),
t('FIG-T-v2',['RES-CHECK-v2','RES-IMPACT-v2'],['project.json:state.figure'],['measurements.csv@v2','results.csv'],'Load figure_shared and data_visualization_learning; make task-adapted brief; produce separate end_to_end and kernel_only panels; render/view outputs',['figure@v2 source script','figure@v2 PNG/PDF','caption@v2','figure QA record'],'Recompute four values; units ms; zero baseline; no invented uncertainty; visual inspection at final size; publish actual hashes'),
t('WRITE-FINAL-v2',['WRITE-DRAFT-v2','FIG-T-v2'],['project.json:state.write'],['results.json','figure@v2','caption@v2'],'Finalize paragraph against actual v2 figure and caption',['paragraph@v2','write consistency record'],'All quoted numbers trace to current v2; scopes separate; regression and data limitations visible'),
t('REV-CHECK-v2',['WRITE-FINAL-v2'],base,['paragraph@v2','figure@v2','results.json'],'Host assign reviewer if available; freeze artifacts and check numerical/scope/claim consistency',['review record@v2'],'Actual review evidence identifies inspected bytes; cannot label author self-check independent review'),
t('BG-REUSE',['RES-IMPACT-v2'],['project.json:state.background'],['concept.txt@v1','background@v1 missing'],'Locate historical background output; verify source/version/scope and absence of performance dependencies',['background applicability record'],'Actual historical output inspected and hash-bound; otherwise remains blocked','blocked','background@v1 output bytes not provided; concept input alone does not validate it'),
t('REV-VERIFY-FINDING',['REV-CHECK-v2'],base,['actual finding envelope absent','current artifact snapshot'],'Verify revised finding and preserve original ID/history; distinguish error/gap/preference; version changed evidence',['verified finding and affected dependency map'],'Actual evidence supports or refutes each finding; limited stale descendants; no auto rewrite','blocked','No actual review finding/message received; conditional recovery plan only'),
t('COM-RECOVER',['REV-VERIFY-FINDING'],base,['immutable revision intent absent','real original seq absent','trusted inbox/Engine ownership absent'],'Ownership/auth check; status exact receipt check; publish same envelope successfully before needs_revision ACK; replay exact intent after interruption',['delivery status and receipt evidence'],'Real publish/seq/ack readback; refs valid; conflicts/budget errors stay pending; no exactly-once claim','blocked','No original delivery, real seq or approved host mailbox adapter in this role task'),
t('REV-REPAIR',['COM-RECOVER'],base,['verified finding','current figure/paragraph hashes'],'Repair only confirmed affected FIG/WRITE claims; deliver revision before acknowledging request',['new immutable artifacts and handoff refs'],'Current hashes reflect repair; original finding preserved; at most two revision rounds','blocked','Depends on actual verified and delivered repair request'),
t('REV-RECHECK',['REV-REPAIR'],base,['original finding criteria','old/new artifact hashes'],'Original reviewer reevaluates new output; append scientific closure separate from consumption',['closure record or unresolved finding'],'Closure binds original finding ID, both artifact hashes and actual recheck evidence; receipt alone insufficient','blocked','Actual reviewer/repair artifacts absent')]
chain={'schema':'bounded-coordination-plan/v1','run_id':run,'plan_version':1,'source_task_list':'project.json + task.txt (no project root TASK.md supplied to this role)','runtime':{'execution_mode':'manual staged coordinator analysis','engine_loaded':False,'scheduler_started':False,'db':None,'monitor_id':None,'host_execution_record':'maintained separately by parent; not fabricated here'},'input_version':'measurements.csv@v2','input_version_authority':'project.json:change','keep':[{'id':'collect','version':'v1','scope':'historical declaration only','revalidated':False},{'id':'background','version':'v1','scope':'historical declaration and concept input; missing output','revalidated':False}],'invalidate':[{'id':'figure@v1','reason':'depends on changed measurements@v1; stale for v2 use'},{'id':'write/v1-input-binding','reason':'unstarted old dispatch must be replaced with v2 analysis/figure dependency'}],'tasks':nodes,'conditional_communication':{'executed':False,'review_finding_present':False,'actual_original_seq':None,'recovery_order':['validate Engine lease/cancel/auth/single consumer/run/refs','persist immutable intent with original seq, finding ID, hashes, complete envelope and exact receipt/reason','status checks original delivery and exact existing receipt','publish saved envelope with identical event_id and bytes; verify success or exact dedup seq','only then acknowledge original needs_revision','replay same intent after interruption; preserve receipt; migrate changed refs/goal to new run','repair then deliver before acknowledging request; original reviewer checks new hashes before separate closure'],'revision_limit':2,'semantic_closure_separate_from_receipt':True,'limits':'No atomic publish+ACK or exactly-once side-effect guarantee; no adapter execution claim'},'goal_status':'coordination analysis performed; figure/final writing and independent review not complete'}
(p/'task_chain.json').write_text(json.dumps(chain,ensure_ascii=False,indent=2)+'\n')
