import json,hashlib,ast
from pathlib import Path
B=Path('/workspace/scratch/c12f3d9f92bd');O=Path(__file__).parent;I=O.parents[2]/'inputs';R=B/'agent'
def read(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):(O/n).write_text(json.dumps(x,indent=2)+'\n')
c=read(I/'candidate.json');checks=read(O/'refchecks.json'); obs=read(O/'full-observations.json');tree=ast.parse((R/'agent_runtime/core.py').read_text());methods={x.name:[y.name for y in x.body if isinstance(y,(ast.FunctionDef,ast.AsyncFunctionDef))] for x in tree.body if isinstance(x,ast.ClassDef)}
f=dict(finding_id='REV-F001',snapshot_id=c['candidate_id'],category='reporting',severity='minor',confidence='high',assertion_type='confirmed_error',status='confirmed',title='Workflow names Engine.current(), but the frozen API provides Context.current()',location=[dict(path='workflows/agent_communication_workflow.md',line=70),dict(path='plugins/research-assistant/skills/research-assistant/references/agent_communication_workflow.md',line=72)],evidence=[dict(path='agent_runtime/core.py',sha256=sha(R/'agent_runtime/core.py'),lines=[186,224],observation='Context.current at 195-199 checks cancellation, token, task status and lease; the complete Engine class has no current method.'),dict(path='consumer/consumer.py',sha256=sha(I/'consumer/consumer.py'),lines=[41,47],observation='Executed guard correctly calls context.current(), independently checks host authorization, then logs current/authorized.'),dict(path='workflows/agent_communication_workflow.md',sha256=sha(R/'workflows/agent_communication_workflow.md'),line=70,observation='Existing guard is named Engine.current() in the documented interface.')],why_it_matters='A host implementing the named API literally would encounter a missing Engine method. This is a documentation defect; the actual consumer uses the correct Context method and its observed protocol outcomes remain valid.',verification='Read the entire frozen core.py class definitions and the actual consumer guard; no new experiment required.',resolution_options=['Name Context.current() and the separate host/Engine authorization check in both workflow copies.','Supply an actual version-bound Engine.current alias if that is deliberately intended, and revisit the frozen runtime identity.'],recheckconditions=['New workflow hashes identify both edited copies; both name the actual Context.current API and preserve the separate authorization requirement.','Compare against the unchanged runtime and consumer guard; retain publish-before-ACK, exact saved receipt, single-owner assumption and no-scientific-closure boundaries.'],acceptance=['Static recheck confirms the named guard exists and both workflow copies agree.'],related_findings=[],closure='Not resolved in this audit; no source edits performed.')
tasks=[dict(task_id='REV-T001',finding_ids=['REV-F001'],stage='verify',depends_on=[],owner='research-review',status='done',action='Verify documentation/API mismatch against frozen code',outputs=['refchecks.json','api-symbol-check.json'],done_when='Workflow names Engine.current; full Engine class lacks current and Context has current; actual guard uses Context.'),dict(task_id='REV-T002',finding_ids=['REV-F001'],stage='resolve',depends_on=['REV-T001'],owner='main-ai',status='todo',action='Correct the API name in source workflow and generated copy under authorized source editing scope',done_when='New immutable hashes and correction record available',on_missing_input='blocked until source editing is authorized to the responsible owner'),dict(task_id='REV-T003',finding_ids=['REV-F001'],stage='recheck',depends_on=['REV-T002'],owner='research-review',status='todo',action='Recheck both new workflow copies against actual runtime and original boundaries',done_when=f['recheckconditions'],on_missing_input='blocked; preserve confirmed finding')]
save('api-symbol-check.json',dict(core_sha256=sha(R/'agent_runtime/core.py'),class_methods=methods,Engine_current_exists='current' in methods['Engine'],Context_current_exists='current' in methods['Context']))
save('findings.json',dict(schema_version=1,review_id='REV-W8-CANDIDATE-AUDIT-001',run_id='revision-w8-candidate-audit',input_version='candidate-d95ce4e4',snapshot=c,verdict='bounded_transport_claims_supported_with_minor_documentation_issue',findings=[f],tasks=tasks,scientific_acceptance=False,remaining=['REV-F001 correction and independent recheck','Budget original pending; conflict requires main AI reconciliation','Responsibility author request pending; author revision and original reviewer revalidation unexecuted','No production adapter migration, whole research chain, model/session quality or external side-effect acceptance']))
text='''# Independent frozen candidate audit

REV-W8-CANDIDATE-AUDIT-001 · 2026-10-07 · actual Mailbox delivery seq 1, task REV-03.

**Verdict:** the three bounded local transport claims are supported by the delivered code, process/API records and independently read live SQLite rows. One minor documentation error remains (REV-F001). This is not scientific acceptance, production adapter acceptance, or full research feedback-loop completion. No blocking or major correctness defect was established within the reviewed scope.

## Scope, identity and operations

I applied the frozen research-review SKILL.md, execution.md and relevant workflow sections for correctness, evidence, false-positive checks and stable verify/resolve/recheck handoff. This is a local protocol review, not a venue manuscript review; no venue score, literature novelty claim or network lookup applies. Candidate and producer artifacts were read in full. No rubric, root scores or prior reviewer findings were read. No source edits, consumer reruns, installs, experiments, network calls, artificial session restart or external effects were performed.

Actual API inbox returned seq 1 for research-review in revision-w8-candidate-audit, input candidate-d95ce4e4. It contains four refs (report, consumer, results, hash manifest); these are ordinary audit evidence, with no completion handoff manifest. The review therefore reads and verifies them directly, rather than invoking the inapplicable completion-manifest consume_handoff branch. `inbox.json` preserves the real return; `refchecks.json` preserves 69 successful local SHA/size checks, including all four live refs, 50 manifest members, consumer task/reading identity, three source files against git blobs/embedded source, and both current candidate workflow hashes. `full-observations.json` retains all 52 input files and full scenario API/process/state observations. No hash mismatch occurred. SELECT-only live readbacks of the three owned producer mailbox databases match every captured plan/event/delivery row exactly.

The audit candidate is d95ce4e4a9a79922d692f181eb7203176d7a1a3b460658b54ac1e1b6528c2dca. Its workflow hash is d288fa564ad12b78af63c385ee340e0e436ce3a711492df860922b38b0c2791a and generated Skill copy hash is 8b4e36a0141776abfe77eebf6bda476145d5c3b8c2a9307ea5cdb546bf0fe0a2. The producer identity/report binds earlier single-workflow candidate 7efadc9ff81470205356f4e6c83000fc8d7baab6f32d215947d754f8e6573bea, explicitly excluding its package successor. The common workflow bytes and runtime bytes match, so these observations apply to the shared protocol, not an execution of the whole newer package. I independently checked both newer workflow files: differences are the generated marker and two repository-relative links converted to public URLs; contract body is otherwise identical. The common source commit is c66b5ced2bbb15ef6d42a4c8530256b4152c94ed and actual runtime hash is e4604a9b0ce8852175b4a4f90f10ed98e685f36a7085aa86558b77f076c32300. Package installation, URL availability and broader adapter integration were not tested.

## Claim and evidence audit

| Claim | Independent observation | Assessment |
|---|---|---|
| Publish before original needs_revision ACK survives one child interruption | interruption/api.jsonl lines 9 and 17 show same outgoing envelope, first duplicate=false then duplicate=true at seq 2; line 21 records exact saved receipt for seq 1. fault-process exit -9 and pre-ACK null receipt; replay exit 0. Live rows contain only seed and request. | Supported for one owned consumer, same refs/intent/run, valid existing lease, one child replay. |
| Budget failure preserves original pending delivery | budget plan max_events=1, seed already consumes budget; API final line reports ValueError before ACK; process exit 3; live event count 1 and original null receipt. | Supported; remains unresolved, not accepted or silently expanded. |
| Existing receipt conflict stops before request publication | conflict API line 2 seeds rejected receipt; line 7 records mismatch with saved needs_revision. Process exit 4; live event count 1 and existing rejected receipt unchanged. | Supported; main AI reconciliation remains required. |
| Source describes validation and immutable receipts accurately | communication.py 89–130 validates envelope/run/input/routes/refs before transactional exact dedup, then event budget; 144–163 is separate immutable ACK; 165–171 status retains receipts. | Supported source facts; no combined atomic publish/ACK transaction. |
| Ownership, input, lease, cancellation and authorization guarded | Consumer guard reads current Engine plan and task hash authorization, uses Context.current, checks run/input/owner and reads both refs. API guard records current/authorized=true before observed effects. | Positive-path guard execution supported; lease revocation, cancellation races and multiple-owner fencing not exercised. |
| No scientific closure follows transport | Outgoing author delivery at interruption seq 2 remains unacknowledged; synthetic record has real_experiment=false and scientific_status=not assessed. Engine done is scoped to scenario evidence capture. | Boundary honored. No revision, author request handling or scientific revalidation executed. |

The interruption is a real recorded Python child SIGKILL/replay while the parent Engine dispatch stays alive and its original lease remains valid. It is not a model-session restart or recovery after a host shutdown/lease expiry. Plans and intent are separate immutable per-scenario files; the consumer reads reference contents before effects. Single-consumer preflight is correctly described as an assumption, not a cross-operation lock. The actual runtime permits an ACK-first caller, so prose changes do not migrate other adapters; the report explicitly acknowledges this. Delivery token redaction is documented with raw/redacted digests; delivered hashes and semantic records were verified. Private raw tokens were not exposed; this audit does not independently certify every redaction against private raw bytes.

## Finding and recheck

**REV-F001 (minor, confirmed, high confidence):** workflow line 70 and generated copy line 72 refer to `Engine.current()`. Frozen core.py provides `Context.current()` at 195–199; its complete Engine class has no current method. The actual consumer correctly invokes `context.current()` at 44–45 and performs separate authorization checks. Literal adaptation of the documented API would fail. This does not invalidate the observed consumer outcomes. Correct both documentation copies to the actual Context API while retaining authorization, then recheck new hashes and the original ordering/boundaries. `findings.json` binds the evidence and concrete recheckconditions; `api-symbol-check.json` records complete class-method enumeration. No change or closure was made here.

## Remaining work and handoff

The main AI owns the minor documentation correction and budget/conflict reconciliation. The responsibility author must actually process the pending request, produce a versioned revision and successfully deliver it; the original reviewer must read old/new evidence against the original finding condition before scientific closure. Full completion-manifest consumption, production migration, cross-host concurrency, malicious file replacement, lease expiry, cancellation rejection, model quality/performance and a real code→figure→paper→review→reader chain remain unverified. These are explicit limits, not invented failures or fabricated acceptance tests.

After this evidence review is written, seq 1 is acknowledged **consumed**, solely as processed audit delivery. `mailbox-api.jsonl`, `ack-return.json` and `ack-readback.json` retain the actual operation/result/status/inbox. The receipt does not resolve REV-F001 or any scientific finding.
'''
(O/'audit.md').write_text(text)
print(json.dumps({'written':['audit.md','findings.json','api-symbol-check.json'],'finding_count':1,'severity':'minor','hash_checks_pass':checks['all_pass']}))
